### PR TITLE
Changed all sprintf To snprintf

### PR DESCRIPTION
**Pull request by EvanKropf**
in reference to https://github.com/Open-Acidification/TankController/issues/65

### CODE REVIEW

**Comment by jgfoster** [comment]
The spell checking test has the following output:

```
New misspellings found, please review:\n\n* smprintf\n* snprintf\
```

This tells us that there are two unrecognized words: `smprintf` and `snprintf`. The first one looks like a typo so you should fix it. The second one is legitimate, so should be added as a valid word. This will be done in `.github/actions/spelling/expect.txt` after line 111. Note that we already have `sprintf` as an allowed word and I'd like you to remove that word so that any future use of the old function will be caught.

**Review by jgfoster — APPROVED** [review]
That looks like just what I asked for!

**Review by prestoncarman — APPROVED** [review]
LGTM

**Comment by prestoncarman** [comment]
@all-contributors please add @EvanKropf for code

**Comment by prestoncarman** [comment]
@all-contributors please add @EvanKropf for code

**Pull request merged**
