### PR TITLE
Renamed all test files to add Test to the beginning of the file name

### PR DESCRIPTION
**Pull request by genevea**

### CODE REVIEW

**Review by jgfoster — CHANGES_REQUESTED** [review]
We should have the word "Test" only once in the file name. Since you have added the word "Test" to the front of all the files you should remove the word "Test" from the end of the files. See TestTCLibTest, TestTemperatureControlTest, etc.

**Comment by jgfoster** [comment]
Note also that renaming the headers will require some rearranging of the include statements to satisfy the formatting rules. See test-clang-format for the issues.

**Comment by jgfoster** [comment]
And, thank you for getting involved with our project! Welcome!

**Comment by genevea** [comment]
Thanks for the welcome.  I wanted to start helping out the open-source community and give back since I have made such great use of it over my career.  Addressed all your comments.

**Comment by genevea** [comment]
Funny, the allow edits by maintainer's box is ticked off.

**Comment by genevea** [comment]
In fact, I don't have the write ability to resolve the conflict.

**Comment by jgfoster** [comment]
I believe the process to resolve the conflict would be something like the following in your local clone (I'm writing this from memory and haven't tried it exactly):

- `git checkout main`
- `git add remote upstream  git@github.com:Open-Acidification/TankController.git`
- `git fetch upstream`
- `git merge upstream/main`
- `git checkout issue_38_rename_test_files`
- `git merge main`
- `git add .`
- `git commit -m "merge recent changes from upstream/main"`
- `git push`

With that, GitHub will update the pull request to show your changes.

> Funny, the allow edits by maintainer's box is ticked off.

Alternatively, try ticking that box on to allow me to commit a change to your fork (it would be only to this branch of this project; I wouldn't have access to anything else in your account).

Again, sorry to make this complicated!

**Comment by genevea** [comment]
I did a new push, I think I have it working with the changes.

**Comment by genevea** [comment]
Very new to Github (worked mostly in Gitlab and git CLI).  I think I added you to my repository in case my updated didn't work.  No worries about the work, these things happen all the time.  :)

**Comment by jgfoster** [comment]
Thank you for adding me to your repository. I think we resolved the merge conflicts. It is interesting that I couldn't do it from GitHub but I could do it by merging your changes in my local environment then pushing them to your repository. As to Git, I'm still unsure of a lot of it but I'm managing to make do [this](https://xkcd.com/1597/) sums up my basic attitude. The tests take a while to run (we have an issue for that!), but I'll keep an eye on it and let you know...

**Comment by genevea** [comment]
> Thank you for adding me to your repository. I think we resolved the merge conflicts. It is interesting that I couldn't do it from GitHub but I could do it by merging your changes in my local environment then pushing them to your repository. As to Git, I'm still unsure of a lot of it but I'm managing to make do [this](https://xkcd.com/1597/) sums up my basic attitude. The tests take a while to run (we have an issue for that!), but I'll keep an eye on it and let you know... (By the way, we use GitLab at our University, so I'm often confused jumping between it and GitHub.)

I love xkcd.  It's always so spot on.  That and Dilbert...

**Review by jgfoster — APPROVED** [review]
Looks good. Thanks!

**Comment by prestoncarman** [comment]
@all-contributors please add @genevea for code

**Pull request merged**
