### PR TITLE
Updating MainMenu.cpp C-style pointers to use C++ style pointers

### PR DESCRIPTION
**Pull request by IDzyre**
I changed the C-style pointers in MainMenu.cpp to C++ style pointers.

### CODE REVIEW

**Review by prestoncarman — DISMISSED** [review]
LGTM

**Comment by prestoncarman** [comment]
Looks like you need to add a third parenthesis at the end of each line.

**Comment by jgfoster** [comment]
@IDzyre, Will you be able to make the required edits to get the tests to pass? Let me know if you need help.

**Review by jgfoster — APPROVED** [review]

**Comment by prestoncarman** [comment]
@all-contributors please add @IDzyre for code

**Pull request merged**
