### PR TITLE
Added Double quotes for codacy warnings

### PR DESCRIPTION
**Pull request by TaylorSmith28**
Working on #111.

### CODE REVIEW

**Comment by prestoncarman** [comment]
This  change requires a manual test.

**Comment by jgfoster** [comment]
I think that `scripts/install_libraries.sh` is part of the `arduino_ci` tests. In any case, Taylor and I did a manual test of both edits and I'm satisfied with it.

**Review by jgfoster — APPROVED** [review]
LGTM.

**Comment by prestoncarman** [comment]
@all-contributors please add @TaylorSmith28  for code

**Pull request merged**
